### ISSUE TITLE
Convert UFT-16 strings to UFT-8

### ISSUE THREAD

**Issue by caioferndev** [perplexedMurfy/MarieAssembler#2]
As title says, going to copy/paste Mike's message to me about this here:

Sounds great, I'll set up access to the actual repo so you can just make a branch on it.

One of the items I'd like help on is migrating MarieAssembler.h and MarieAssembler.c from UTF-16 strings to UTF-8 strings. 

Some background on the terms here: On windows, wchar_t refers to a UTF-16 Little Endian(UTF-16LE) code point. Likewise wchar_t* is a UTF-16LE string.

Many strings in these files are spefied as L"foo" which are wide string literals. Change them to u8"foo" so that they are UTF-8 string literals. The same transfomration is needed with charcter literals (L'a' --> u8'a').

Many structures and functions in the two aformentioned files should have their wchar_t* changed to char*.

Function: LoadFileIntoMemory() currently converts formats that it recoginzes into a UTF-16LE string and returns that string. This function should preform the equivlent operation with a UTF-8 String output. 
Function: IncrementFilePosition() should increment File->At by Count Characters. In UTF-8 Characters can be as long as 4 bytes, or as short as 1 byte. In addition, IncrementFilePosition() should return how many bytes File->At was incremented.

Lastly, there are a lot of wprintf() functions that should be converted to their non-wide versions (i.e _snwprintf() --> snprintf())
That should be all.

**Comment by perplexedMurfy** [comment]
This issue is fixed with commit 1d0386007d6251e50f2b5b7d95ff44a15fb91723
