### ISSUE TITLE
Optional args to enable features

### ISSUE THREAD

**Issue by caioferndev** [perplexedMurfy/MarieAssembler#3]
Need args to enable optional features, for example:

- Having debug messages appear in console
- Changing verbosity of said debug messages
- Explicitly stating location where the output should go
- Allowing users to give output files a different name from the original

Mainly want args for the first two features.

**Comment by perplexedMurfy** [comment]
I was just thinking about the latter two during the shower. I'll see what I can do.

**Comment by perplexedMurfy** [comment]
Regarding debug messages: what kind of debug messages are you talking about? Off the top of my head, there are very few areas that have messages that aren't intended to be sent to the end user.

**Comment by caioferndev** [comment]
I'm thinking about having messages to console/file so users can "see" what's currently going on inside the MARIE compiler. Right now, the program is a black box, we don't know what the program is doing until it spits out either a pass or a failure (if it even detects an error, sometimes it's a silent failure).

These messages don't need to be displayed all the time, so we can have messages enabled as an arg, depending on what the user/developer wants (debug, verbose, obnoxious, none).

Also, the MARIE architecture is a learning tool for CS students to have more of an idea how programs are designed for a specific architecture, so I'm pretty sure the console being a little more verbose isn't something anyone is going to complain about.

**Comment by perplexedMurfy** [comment]
> Right now, the program is a black box, we don't know what the program is doing until it spits out either a pass or a failure (if it even detects an error, sometimes it's a silent failure).

A silent failure is a bug in my eyes, there's ***no*** valid reason for the program to fail and not inform the user. 
If you know of cases that produce a silent failure, make an issue regarding it.

> I'm thinking about having messages to console/file so users can "see" what's currently going on inside the MARIE compiler.

Other than spamming the user with what the assembler just parsed, I'm not sure what this internal state is that we would want to show the user. Keep in mind that we already show all information about Identifiers via the Symbol Table output (definition and usages). If you have specific ideas, I'm all ears!

**Comment by caioferndev** [comment]
If the user (or developer) designates the console to be more verbose, we can display info such as the names of the identifiers the compiler recognizes, so yeah, we would be spamming the console with what the assembler just parsed. As to why this would be useful, we can catch weird behavior in the logging without having to step through the source code with a debugger. Again, this is optional for the user/developer and doesn't have to be the default, hence why I'm asking for this as an optional arg.

Also, about the silent failures, yeah, it's a bug and should be reported, but without any sort of logging, pinpointing where an error is occurring becomes much more difficult. If a user reports a bug, they can't provide any sort of useful info other than the inputs they provided; being handed a log of what the compiler is doing can expedite debugging without ever having to enter an editor/debugger.

**Comment by perplexedMurfy** [comment]
>As to why this would be useful, we can catch weird behavior in the logging without having to step through the source code with a debugger.

Personally, I do not see the value of a verbose output in this case over other approaches. If we're fixing a known error, then I doubt that logging will prevent the need for opening a debugger or expedite the process in a significant way. If we're searching for bugs, then I'd rather spend time writing tests than writing logging features.

Perhaps this is something which I need to see for myself in practice before I will think it is a good idea though. Feel free to open another issue/pull request for it. What I will declare is that the implementation of logging features is outside the scope of this issue.

**Comment by caioferndev** [comment]
I'm used to having to resolve issues with users who don't have any internal knowledge of the program, but most of these bugs will be caught by us anyways, so I see your point.

Maybe on a project with a wider userbase. I'll make a separate issue for this and make it low priority.
