### ISSUE TITLE
Optional logging to console/file

### ISSUE THREAD

**Issue by caioferndev** [perplexedMurfy/MarieAssembler#8]
Add logging to console during program execution to see the internal state of the compiler. Essentially, we want to know what values/instructions/(labels/identifiers) the compiler recognizes from the user input as it's being read so we know the text is being interpreted properly.

**Comment by perplexedMurfy** [comment]
Removing good first issue, since knowing what's valuable to log requires familiarity with the code base.

**Comment by perplexedMurfy** [comment]
After consideration, I am going to close this issue. I am not convinced that this program has anything that is worth being logged that isn't already being reported to the user.
